In [ ]:
import numpy as np
print(np.__version__)


2.2.6


In [3]:
tallest_buildings = np.array([2717, 2227, 2073, 1972, 1966, 1819, 1776])
print("Printing in feets",tallest_buildings*0.3048)

Printing in feets [828.1416 678.7896 631.8504 601.0656 599.2368 554.4312 541.3248]


In [4]:
temperatures = np.array([[50, 51, 54, 59, 59, 53, 54, 51],
                         [45, 50, 38, 44, 40, 46, 43, 39]])

print(np.min(temperatures))       
print(np.max(temperatures))      
print(np.sum(temperatures))      
print(np.average(temperatures))   

38
59
776
48.5


In [7]:
temperatures = np.array([[50, 51, 54, 59, 59, 53, 54, 51],
                         [45, 50, 38, 44, 40, 46, 43, 39]])

print(np.sum(temperatures, axis=0) )
print(np.min(temperatures, axis=1)  ) 

[ 95 101  92 103  99  99  97  90]
[50 38]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 

print(arr.shape)     

(4, 3)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
new_arr = arr.reshape(2, 4)

print(new_arr)


[[1 2 3 4]
 [5 6 7 8]]


In [14]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.shape)

(28,)


In [15]:
weekly_results = month_results.reshape(4, 7)
print(weekly_results)

[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]


In [17]:
arr = np.arange(start=2, stop=10, step=2)

print(arr)  

[2 4 6 8]


In [18]:
passengers = np.array([
   [1, 0, 3, 22],
   [2, 1, 1, 38],
   [3, 1, 3, 26],
   [4, 1, 1, 35],
   [5, 0, 3, 35],
   [6, 0, 3, 18],
   [7, 0, 1, 54],
   [8, 0, 3, 2],
   [9, 1, 3, 27],
  [10, 1, 2, 14],
  [11, 1, 3, 4],
  [12, 1, 1, 58],
  [13, 0, 3, 20],
  [14, 0, 3, 39],
  [15, 0, 3, 14],
  [16, 1, 2, 55],
  [17, 0, 3, 2],
  [18, 1, 2, 12],
  [19, 0, 3, 31],
  [20, 1, 3, 8],
  [21, 0, 2, 35],
  [22, 1, 2, 34],
  [23, 1, 3, 15],
  [24, 1, 1, 28],
  [25, 0, 3, 8],
  [26, 1, 3, 38],
  [27, 0, 3, 2],
  [28, 0, 1, 1],
  [29, 1, 3, 5],
  [30, 0, 3, 18],
  [31, 0, 1, 40],
  [32, 1, 1, 70],
  [33, 1, 3, 33],
  [34, 0, 2, 66],
  [35, 0, 1, 28],
  [36, 0, 1, 42],
  [37, 1, 3, 5],
  [38, 0, 3, 18],
  [39, 0, 3, 18],
  [40, 1, 3, 14],
  [41, 0, 3, 40],
  [42, 0, 2, 27],
  [43, 0, 3, 29],
  [44, 1, 2, 0],
  [45, 1, 3, 19],
  [46, 0, 3, 33],
  [47, 0, 3, 14],
  [48, 1, 3, 22],
  [49, 0, 3, 41],
  [50, 0, 3, 18]
])

In [19]:
print(passengers.shape)

(50, 4)


In [ ]:
avg_age=np.average(passengers[:,3])
print(avg_age)

25.5


In [ ]:
oldest=np.max(passengers[:,3])
print(oldest)


70


In [23]:
yoyngest=np.min(passengers[:,3])
print(yoyngest)

0


printing how many survived

In [48]:
count=0
survived=0
for i in passengers:
    if(i[1] == 1):
        print(i)
        survived+=1
    count+=1
print('Total surviced : ',survived)
print('Average of survival: ',survived/count)

[ 2  1  1 38]
[ 3  1  3 26]
[ 4  1  1 35]
[ 9  1  3 27]
[10  1  2 14]
[11  1  3  4]
[12  1  1 58]
[16  1  2 55]
[18  1  2 12]
[20  1  3  8]
[22  1  2 34]
[23  1  3 15]
[24  1  1 28]
[26  1  3 38]
[29  1  3  5]
[32  1  1 70]
[33  1  3 33]
[37  1  3  5]
[40  1  3 14]
[44  1  2  0]
[45  1  3 19]
[48  1  3 22]
Total surviced :  22
Average of survival:  0.44


Now i will Find Percentage of passengers survived based on their Class

In [36]:
upper_class=[]
middle_class=[]
lower_class=[]
for i in passengers:
    if(i[2] == 1):
        upper_class.append(i)
    elif(i[2] == 2):
        middle_class.append(i)
    else:
        lower_class.append(i)



In [ ]:
upper_class=np.array(upper_class)
middle_class=np.array(middle_class)
lower_class=np.array(lower_class)


In [49]:
upper_class_survived = 0
for i in upper_class:
    if(i[1] == 1):
        upper_class_survived+=1
print('Upper class survived : ',upper_class_survived)
print("Average :",upper_class_survived/len(upper_class))
 


Upper class survived :  5
Average : 0.5


In [50]:
middle_class_survived = 0
for i in middle_class:  
    if(i[1] == 1):
        middle_class_survived+=1 
print('Middle class survived : ',middle_class_survived)
print("Average :",middle_class_survived/len(middle_class))

Middle class survived :  5
Average : 0.625


In [51]:
lower_class_survived = 0
for i in lower_class:
    if(i[1] == 1):
        lower_class_survived+=1
print('Lower class survived : ',lower_class_survived)
print("Average :",lower_class_survived/len(lower_class))

Lower class survived :  12
Average : 0.375
